export enum CvStatus {
  CREATED = 'CREATED',
  AVATAR_UPLOADED = 'AVATAR_UPLOADED',
  PDF_GENERATED = 'PDF_GENERATED',
  PREVIEW_GENERATED = 'PREVIEW_GENERATED',
  PREVIEW_THUMBNAIL_GENERATED = 'PREVIEW_THUMBNAIL_GENERATED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  DELETED = 'DELETED',
}
