export enum AiDraftCvStatus {
  CREATED = 'CREATED',
  AVATAR_UPLOADED = 'AVATAR_UPLOADED',
  GENERATING_CONTENT = 'GENERATING_CONTENT',
  CONTENT_GENERATED = 'CONTENT_GENERATED',
  PDF_GENERATED = 'PDF_GENERATED',
  PREVIEW_GENERATED = 'PREVIEW_GENERATED',
  PREVIEW_THUMBNAIL_GENERATED = 'PREVIEW_THUMBNAIL_GENERATED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  DELETED = 'DELETED',
}
